export async function fetchTaxonData(character) {
    try {
    //   const response = await fetch(`https://your-api-url/taxa?character=${character}`);
    //   const data = await response.json();
      return data;
    } catch (error) {
      console.error("Failed to fetch taxon data:", error);
    }
}

const data = [
    {
        "id": 88,
        "species_id": 88,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "dusky yellow",
        "pairs_of_supraantennals": "0",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "light brown",
        "first_flagellomere_shape": "laterally compressed under arista",
        "palpus_color": "light brown",
        "palpus_shape": "cylindrical, increasing in diameter toward apex",
        "labrum_shape": "weak",
        "labellum_shape": "normal",
        "eye_size": "normal",
        "number_of_notopleural_setae": "",
        "scutum_color": "dusky yellow",
        "scutellum_color": "dusky yellow",
        "anterior_to_posterior_scutellar_setae_ratio": "near equal",
        "pleuron_color": "dusky yellow",
        "anepisternal_setae": "absent",
        "forefemur_color": "dusky yellow",
        "midfemur_color": "dusky yellow",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "dusky yellow",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "slightly inflated",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "fades before R1",
        "R2 plus 3": "",
        "halter_color": "dusky yellow",
        "abdominal_T1_T2_color": "dusky yellow",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "dusky yellow",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "greatly narrowing posteriorly",
        "posterodorsal_to_posteroventral_setae_S6_length": "equal",
        "setae_venter_abdomen": "almost bare",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "LUD_COL_1 kurtcobaini",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "Oreophilophora_LUD_COL_1_habitus_LACMENT067039 LUD COL1_web.png",
        "terminalia_lateral_image": "LACM ENT 067039 LUD_COL_1 oviscape lateral stacked final web.jpg",
        "terminalia_dorsal_image": "LACM ENT 067039 LUD_COL_1 oviscape dorsal stacked web.jpg"
    },
    {
        "id": 89,
        "species_id": 89,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "brown",
        "pairs_of_supraantennals": "1",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "below lower interfrontals",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "brown",
        "first_flagellomere_shape": "pointed under arista",
        "palpus_color": "dusky yellow",
        "palpus_shape": "",
        "labrum_shape": "",
        "labellum_shape": "",
        "eye_size": "reduced",
        "number_of_notopleural_setae": "",
        "scutum_color": "brown",
        "scutellum_color": "dark brown",
        "anterior_to_posterior_scutellar_setae_ratio": "near equal",
        "pleuron_color": "brown",
        "anepisternal_setae": "absent",
        "forefemur_color": "light brown",
        "midfemur_color": "light brown",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "light brown",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "normal",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "fades before R1",
        "R2 plus 3": "",
        "halter_color": "light brown",
        "abdominal_T1_T2_color": "brown",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "brown",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "greatly narrowing posteriorly",
        "posterodorsal_to_posteroventral_setae_S6_length": "longer",
        "setae_venter_abdomen": "",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "LUD_COL_2 mikrommatos",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "Oreophilophora_LACMENT154064_LUDCOL2_web.png",
        "terminalia_lateral_image": "LACM ENT 154064 LUD_COL _2 oviscape lateral stack final web.jpg",
        "terminalia_dorsal_image": "LACM ENT 154064 LUD_COL_2 oviscape oblique stacked final web.jpg"
    },
    {
        "id": 90,
        "species_id": 90,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "dusky yellow",
        "pairs_of_supraantennals": "1",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "even with lower interfrontals",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "dusky yellow",
        "first_flagellomere_shape": "laterally compressed under arista",
        "palpus_color": "yellow",
        "palpus_shape": "",
        "labrum_shape": "minute",
        "labellum_shape": "",
        "eye_size": "normal",
        "number_of_notopleural_setae": "",
        "scutum_color": "dusky yellow",
        "scutellum_color": "dusky yellow",
        "anterior_to_posterior_scutellar_setae_ratio": "near equal",
        "pleuron_color": "dusky yellow",
        "anepisternal_setae": "absent",
        "forefemur_color": "yellow",
        "midfemur_color": "yellow",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "yellow",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "slightly inflated",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "fades before R1",
        "R2 plus 3": "",
        "halter_color": "yellow",
        "abdominal_T1_T2_color": "dusky yellow",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "dusky yellow",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "",
        "posterodorsal_to_posteroventral_setae_S6_length": "",
        "setae_venter_abdomen": "",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "LUD_CR_1_scottweilandi",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "Oreophilophora_LACMENT035012_LUD_CR1_web.png",
        "terminalia_lateral_image": "LACM ENT 035012 LUD_CR_1 oviscape lateral stacked final web.jpg",
        "terminalia_dorsal_image": "LACM ENT 035012 LUD_CR_1 oviscape dorsal stacked final web.jpg"
    },
    {
        "id": 91,
        "species_id": 91,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "brown",
        "pairs_of_supraantennals": "1",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "above lower interfrontals",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "brown",
        "first_flagellomere_shape": "laterally compressed under arista",
        "palpus_color": "brown",
        "palpus_shape": "",
        "labrum_shape": "minute",
        "labellum_shape": "",
        "eye_size": "normal",
        "number_of_notopleural_setae": "",
        "scutum_color": "light brown",
        "scutellum_color": "light brown",
        "anterior_to_posterior_scutellar_setae_ratio": "near equal",
        "pleuron_color": "light brown",
        "anepisternal_setae": "absent",
        "forefemur_color": "light brown",
        "midfemur_color": "light brown",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "light brown",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "normal",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "fades before R1",
        "R2 plus 3": "",
        "halter_color": "light brown",
        "abdominal_T1_T2_color": "brown",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "brown",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "",
        "posterodorsal_to_posteroventral_setae_S6_length": "",
        "setae_venter_abdomen": "",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "LUD_CR2_zurquiensis",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "LACM ENT 048656 LUD CR2 habitus lateral stacked final web.jpg",
        "terminalia_lateral_image": "LACM ENT 048656 LUD CR2 oviscape lateral stacked final web.jpg",
        "terminalia_dorsal_image": "LACM ENT 048656 LUD CR2 oviscape dorsal stacked final web.jpg"
    },
    {
        "id": 92,
        "species_id": 92,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "dusky yellow",
        "pairs_of_supraantennals": "1",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "even with lower interfrontals",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "yellow-brown",
        "first_flagellomere_shape": "laterally compressed under arista",
        "palpus_color": "dusky yellow",
        "palpus_shape": "",
        "labrum_shape": "minute",
        "labellum_shape": "",
        "eye_size": "normal",
        "number_of_notopleural_setae": "",
        "scutum_color": "dusky yellow",
        "scutellum_color": "dusky yellow",
        "anterior_to_posterior_scutellar_setae_ratio": "",
        "pleuron_color": "dusky yellow",
        "anepisternal_setae": "absent",
        "forefemur_color": "dusky yellow",
        "midfemur_color": "dusky yellow",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "dusky yellow",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "slightly inflated",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "fades before R1",
        "R2 plus 3": "",
        "halter_color": "dusky yellow",
        "abdominal_T1_T2_color": "dusky yellow",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "dusky yellow",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "",
        "posterodorsal_to_posteroventral_setae_S6_length": "",
        "setae_venter_abdomen": "",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "MY_20_chriscornelli",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "Oreophilophora_LACMENT065499_MY_20_web.png",
        "terminalia_lateral_image": "LACM ENT 065499 MY 20 oviscape lateral final web.jpg",
        "terminalia_dorsal_image": "LACM ENT 065499 MY 20 oviscape dorsal stacked final web.jpg"
    },
    {
        "id": 93,
        "species_id": 93,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "dusky yellow",
        "pairs_of_supraantennals": "0",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "dusky yellow",
        "first_flagellomere_shape": "laterally compressed under arista",
        "palpus_color": "yellow",
        "palpus_shape": "short",
        "labrum_shape": "minute",
        "labellum_shape": "normal",
        "eye_size": "normal",
        "number_of_notopleural_setae": "",
        "scutum_color": "dusky yellow",
        "scutellum_color": "dusky yellow",
        "anterior_to_posterior_scutellar_setae_ratio": "near equal",
        "pleuron_color": "yellow",
        "anepisternal_setae": "absent",
        "forefemur_color": "yellow",
        "midfemur_color": "yellow",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "yellow",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "normal",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "fades before R1",
        "R2 plus 3": "",
        "halter_color": "dusky yellow",
        "abdominal_T1_T2_color": "light brown",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "light brown",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "",
        "posterodorsal_to_posteroventral_setae_S6_length": "",
        "setae_venter_abdomen": "",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "LUD_DOM1_laynestaleyi",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "Oreophilophora_CMNH-293687_LUD_DOM1_laynestaleyi_web.jpg",
        "terminalia_lateral_image": "CMNH 293687 LUD_DOM_1 oviscape lateral stacked final web.jpg",
        "terminalia_dorsal_image": "CMNH 293687 LUD_DOM_1 oviscape dorsal stacked final web.jpg"
    },
    {
        "id": 94,
        "species_id": 94,
        "sex": "female",
        "min_body_length": 0,
        "max_body_length": 0,
        "frons_color": "yellow-brown",
        "pairs_of_supraantennals": "1",
        "lower_to_upper_sa_ratio": "",
        "upper_supraantennal_position": "above lower interfrontals",
        "lower_interfrontals_position": "",
        "first_flagellomere_color": "dusky yellow",
        "first_flagellomere_shape": "laterally compressed under arista",
        "palpus_color": "dusky yellow",
        "palpus_shape": "",
        "labrum_shape": "minute",
        "labellum_shape": "normal",
        "eye_size": "normal",
        "number_of_notopleural_setae": "",
        "scutum_color": "yellow",
        "scutellum_color": "yellow",
        "anterior_to_posterior_scutellar_setae_ratio": "near equal",
        "pleuron_color": "dusky yellow",
        "anepisternal_setae": "absent",
        "forefemur_color": "yellow",
        "midfemur_color": "yellow",
        "midtibia_to_tibia_palisade_ratio": "",
        "hind_femur_color": "yellow",
        "hind_femur_maculation": "absent",
        "min_wing_length": 0,
        "max_wing_length": 0,
        "costal_vein": "normal",
        "min_costal_length": 0,
        "max_costal_length": 0,
        "vein_sc": "reaches R1",
        "R2 plus 3": "",
        "halter_color": "dusky yellow",
        "abdominal_T1_T2_color": "dusky yellow",
        "abdominal_T2_setation": "",
        "abdominal_T5_color": "dusky yellow",
        "abdominal_T5_posterior_setae": "",
        "abdominal_T6_shape": "",
        "posterodorsal_to_posteroventral_setae_S6_length": "",
        "setae_venter_abdomen": "",
        "family": "Phoridae",
        "genus": "Oreophilophora",
        "specific_epithet": "LUD_COL3_iguaquensis",
        "year": 2021,
        "diagnosis": "",
        "habitus_image": "LACM ENT 153986 LUD COL3 habitus lateral stack final web.jpg",
        "terminalia_lateral_image": "LACM ENT 153986 LUD COL3 oviscape lateral stack final web.jpg",
        "terminalia_dorsal_image": "LACM ENT 153986 LUD COL3 oviscape dorsal stack final web.jpg"
    }
]